-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v0.9.2
    hooks:
    -   id: trailing-whitespace
        name: Trim Trailing Whitespace
        description: This hook trims trailing whitespace.
        entry: trailing-whitespace-fixer
        language: python
        types: [text]
    -   id: autopep8-wrapper
-   repo: git://github.com/celestian/pytest-mirror
    sha: '47360e705f602e7c022b7c7ea3c989fba74e6d0f'  # Use the sha / tag you want to point at
    hooks:
    -   id: tox
        types: []
        args:
        -   '-c ./tox.ini'
