repos:
-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v0.9.3
    hooks:
    -   id: trailing-whitespace
        name: Trim Trailing Whitespace
        description: This hook trims trailing whitespace.
        entry: trailing-whitespace-fixer
        language: python
        types: [text]
    -   id: autopep8-wrapper
-   repo: local
    hooks:
    -   id: tox-py36
        name: tox py36
        entry: ./.pre-commit-scripts/check-tox.sh
        language: script
        types: []
        args:
        -   '-c ./tox.ini'
        -   '-e py36'
    -   id: tox-pylint
        name: tox pylint
        entry: ./.pre-commit-scripts/check-tox.sh
        language: script
        types: []
        args:
        -   '-c ./tox.ini'
        -   '-e pylint'
